(function(){
 "use strict";
 const VERSION="1.2.1";
 const ASSET_URL="/registry/assets.json";
 const VARIANT_URL="/registry/asset-variants.json";
 let cache=null,variantCache=null;
 const clone=value=>JSON.parse(JSON.stringify(value));
 async function fetchJson(url,key){const response=await fetch(`${url}?_${key}=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`${key} returned HTTP ${response.status}`);return response.json();}
 async function load(options={}){
  if(cache&&variantCache&&!options.force)return cache;
  [cache,variantCache]=await Promise.all([fetchJson(ASSET_URL,"assets"),fetchJson(VARIANT_URL,"variants")]);
  const report=validate(cache,variantCache);
  if(!report.consistent)throw new Error(`Asset Intelligence is inconsistent: ${report.errors.map(x=>x.code).join(", ")}`);
  const detail={...snapshot(),validation:report};
  window.CasaEvents?.publish?.("asset-intelligence:ready",detail);
  window.dispatchEvent(new CustomEvent("casa:asset-intelligence:ready",{detail}));
  return cache;
 }
 function all(filter={}){return (cache?.items||[]).filter(item=>(!filter.type||item.type===filter.type)&&(!filter.status||item.lifecycle_status===filter.status)&&(!filter.orphanOnly||item.standalone===true)&&(!filter.readiness||item.readiness?.level===filter.readiness)).map(clone);}
 function get(id){const item=(cache?.items||[]).find(x=>x.id===id);return item?clone(item):null;}
 function search(query,options={}){const term=String(query||"").trim().toLowerCase();if(!term)return [];return (cache?.items||[]).filter(item=>[item.id,item.title,item.path,item.type,...(item.topics||[])].filter(Boolean).some(v=>String(v).toLowerCase().includes(term))).slice(0,options.limit||50).map(clone);}
 function variants(id){const plan=(variantCache?.plans||[]).find(x=>x.asset_id===id);return plan?clone(plan):null;}
 function variantQueue(filter={}){return (variantCache?.plans||[]).filter(plan=>(!filter.readyOnly||plan.publication?.ready)&&(!filter.blockedOnly||(plan.publication?.blockers||[]).length)&&(!filter.pendingOnly||(plan.variants||[]).some(v=>v.status==="planned"))).map(clone);}
 function publicationReadiness(id){const plan=variants(id);if(!plan)return null;return clone({asset_id:id,ready:Boolean(plan.publication?.ready),blockers:plan.publication?.blockers||[],required_variants:plan.publication?.required_variant_ids||[],variant_status:(plan.variants||[]).map(v=>({id:v.id,status:v.status,target_path:v.target_path}))});}
 function issues(){return (cache?.items||[]).flatMap(item=>{const out=[];if(item.lifecycle_status==="active"&&item.type==="image"&&!String(item.alt_text||"").trim())out.push({asset_id:item.id,severity:"warning",code:"missing-alt-text"});if(item.type==="image"&&(!item.width||!item.height))out.push({asset_id:item.id,severity:"info",code:"missing-dimensions"});if(item.standalone)out.push({asset_id:item.id,severity:"info",code:"standalone-asset"});if(item.readiness?.level==="blocked")out.push({asset_id:item.id,severity:"warning",code:"asset-not-ready",score:item.readiness.score});const publication=publicationReadiness(item.id);for(const blocker of publication?.blockers||[])out.push({asset_id:item.id,severity:"info",code:blocker});return out;});}
 function relations(id){const item=get(id);return item?{asset_id:id,topics:item.topics||[],content:item.related_content||[],relation_count:item.relation_count||0}:null;}
 function readiness(id){const item=get(id);return item?clone(item.readiness):null;}
 function recommendations(id){const item=get(id);if(!item)return [];const out=[];const r=item.readiness||{};if(!r.accessibility)out.push({priority:"high",action:"add-alt-text"});if(!r.dimensions)out.push({priority:"medium",action:"capture-dimensions"});if((r.variant_count||0)<3)out.push({priority:"medium",action:"generate-responsive-variants"});if(!(r.relationship_count||0))out.push({priority:"low",action:"review-content-relationships"});return out;}
 function validate(data=cache,variantData=variantCache){const errors=[],ids=new Set(),paths=new Set(),levels=new Set(["ready","review","blocked"]),planIds=new Set();for(const item of data?.items||[]){if(!item.id||!item.type||!item.path)errors.push({code:"incomplete-asset",id:item.id||null});if(ids.has(item.id))errors.push({code:"duplicate-asset-id",id:item.id});ids.add(item.id);if(paths.has(item.path))errors.push({code:"duplicate-asset-path",path:item.path});paths.add(item.path);if(!(data?.asset_types||[]).includes(item.type))errors.push({code:"unknown-asset-type",id:item.id,type:item.type});if(!item.readiness||!Number.isFinite(item.readiness.score)||!levels.has(item.readiness.level))errors.push({code:"invalid-readiness",id:item.id});if((item.related_content||[]).length!==(item.relation_count||0))errors.push({code:"relation-count-drift",id:item.id});}for(const plan of variantData?.plans||[]){if(planIds.has(plan.asset_id))errors.push({code:"duplicate-variant-plan",id:plan.asset_id});planIds.add(plan.asset_id);if(!ids.has(plan.asset_id))errors.push({code:"orphan-variant-plan",id:plan.asset_id});if(plan.source_immutable!==true||plan.generation_mode!=="non-destructive")errors.push({code:"unsafe-variant-policy",id:plan.asset_id});const variantIds=new Set();for(const variant of plan.variants||[]){if(variantIds.has(variant.id))errors.push({code:"duplicate-variant-id",id:plan.asset_id,variant:variant.id});variantIds.add(variant.id);if(!Number.isInteger(variant.width)||variant.width<=0)errors.push({code:"invalid-variant-width",id:plan.asset_id,variant:variant.id});}}for(const id of ids)if(!planIds.has(id))errors.push({code:"missing-variant-plan",id});return {consistent:errors.length===0,errors,asset_count:data?.items?.length||0,variant_plan_count:variantData?.plans?.length||0,issue_count:issues().length};}
 function impact(id){const item=get(id);if(!item)return null;return {asset:item,usage_count:item.usage_count||0,relation_count:item.relation_count||0,standalone:Boolean(item.standalone),related_content:item.related_content||[],issues:issues().filter(x=>x.asset_id===id),recommendations:recommendations(id),variants:variants(id),publication:publicationReadiness(id)};}
 function snapshot(){const report=validate();const list=cache?.items||[],plans=variantCache?.plans||[];return {version:VERSION,registry_version:cache?.version||null,variant_registry_version:variantCache?.version||null,ready:Boolean(cache&&variantCache),asset_count:list.length,active_count:list.filter(x=>x.lifecycle_status==="active").length,standalone_count:list.filter(x=>x.standalone).length,ready_count:list.filter(x=>x.readiness?.level==="ready").length,review_count:list.filter(x=>x.readiness?.level==="review").length,blocked_count:list.filter(x=>x.readiness?.level==="blocked").length,variant_plan_count:plans.length,publishable_count:plans.filter(x=>x.publication?.ready).length,pending_variant_count:plans.flatMap(x=>x.variants||[]).filter(x=>x.status==="planned").length,issue_count:report.issue_count,consistent:report.consistent};}
 window.CasaAssetIntelligence={version:VERSION,load,all,get,search,issues,relations,readiness,recommendations,variants,variantQueue,publicationReadiness,impact,validate,snapshot,get data(){return cache},get variantData(){return variantCache}};
 window.CasaCore?.modules?.register?.({id:"asset-intelligence",version:VERSION,capabilities:["assets.inventory","assets.search","assets.issues","assets.impact","assets.relations","assets.readiness","assets.recommendations","assets.variants","assets.variant-queue","assets.publication-readiness","assets.validate","assets.snapshot"]});
 load().catch(error=>window.CasaEvents?.publish?.("asset-intelligence:error",{message:error.message}));
})();
